

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mc-backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data        # ← ДОБАВЬ ЭТО
    environment:
      - RESET_DB=false
    networks:
      - mc-net
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: mc-frontend
    ports:
      - "80:80"
    volumes:
      # Статика фронтенда
      - ./frontend:/usr/share/nginx/html:ro
      # Конфиг nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - mc-net
    restart: unless-stopped

networks:
  mc-net:
    driver: bridge
